# Generated by Django 5.0.6 on 2024-07-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='added_by',
        ),
    ]
