# Use postgres/example user/password credentials
version: '3.9'

services:

  db1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
    ports:
      - "5432:5432"

volumes:
  pgdata: